# Generated by Django 4.2.7 on 2023-11-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('cod_asig', models.IntegerField(primary_key=True, serialize=False)),
                ('unidad_credito', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('requisito', models.ManyToManyField(blank=True, to='inscription.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('cod_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('cedula', models.IntegerField()),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('cod_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ci_profesor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('cod_seccion', models.IntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='estudiante_asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(db_column='cod_asig', on_delete=django.db.models.deletion.CASCADE, to='inscription.asignatura')),
                ('estudiante', models.ForeignKey(db_column='cod_estudiante', on_delete=django.db.models.deletion.CASCADE, to='inscription.estudiante')),
            ],
        ),
    ]
